apiVersion: v1
kind: Secret
metadata:
  name: bizflycloud-credentials
  namespace: karpenter
type: Opaque
stringData:
  email: "your-email@example.com"  # Replace with your BizFly Cloud email
  password: "your-password"        # Replace with your BizFly Cloud password 