apiVersion: v1
kind: Secret
metadata:
  name: bizflycloud-credentials
  namespace: karpenter
type: Opaque
stringData:
  # Authentication method: "password" or "application_credential"
  auth-method: "application_credential"
  
  # Password authentication
  email: "your-email@example.com"
  password: "your-password"
  
  # Application credential authentication
  app-cred-id: "****"
  app-cred-secret: "****"
  
  # Other configuration
  region: "****"
  api-url: "****"
  tenant-id: "****" 