apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter
  namespace: karpenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karpenter
      app.kubernetes.io/instance: karpenter
      app.kubernetes.io/name: karpenter
  template:
    metadata:
      labels:
        app: karpenter
        app.kubernetes.io/instance: karpenter
        app.kubernetes.io/name: karpenter
    spec:
      serviceAccountName: karpenter
      containers:
      - name: karpenter
        image: cr-hn-1.bizflycloud.vn/cecd854937c8421b81d1d73789acad52/karpenter:v1.2.6
        env:
        - name: KARPENTER_LOG_LEVEL
          value: debug
        - name: KARPENTER_CLOUD_PROVIDER
          value: bizflycloud
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG
          value: default
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_NAMESPACE
          value: karpenter
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_NAME
          value: default
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_API_VERSION
          value: karpenter.bizflycloud.com/v1
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_KIND
          value: ProviderConfig
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_REGION
          value: HN2
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_SECRET_REF_NAME
          value: bizflycloud-credentials
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_SECRET_REF_NAMESPACE
          value: karpenter
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_CLOUD_CONFIG_API_ENDPOINT
          value: https://manage.bizflycloud.vn/api
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_IMAGE_CONFIG_IMAGE_ID
          value: ubuntu-20.04
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_IMAGE_CONFIG_ROOT_DISK_SIZE
          value: "20"
        # Bizfly Cloud authentication environment variables
        - name: BIZFLY_CLOUD_AUTH_METHOD
          valueFrom:
            secretKeyRef:
              name: bizflycloud-credentials
              key: auth-method
        - name: BIZFLY_CLOUD_EMAIL
          valueFrom:
            secretKeyRef:
              name: bizflycloud-credentials
              key: email
        - name: BIZFLY_CLOUD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bizflycloud-credentials
              key: password
        - name: BIZFLY_CLOUD_APP_CRED_ID
          valueFrom:
            secretKeyRef:
              name: bizflycloud-credentials
              key: app-cred-id
        - name: BIZFLY_CLOUD_APP_CRED_SECRET
          valueFrom:
            secretKeyRef:
              name: bizflycloud-credentials
              key: app-cred-secret
        - name: BIZFLY_CLOUD_REGION
          valueFrom:
            secretKeyRef:
              name: bizflycloud-credentials
              key: region
        - name: BIZFLY_CLOUD_API_URL
          valueFrom:
            secretKeyRef:
              name: bizflycloud-credentials
              key: api-url
        - name: BIZFLY_CLOUD_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: bizflycloud-credentials
              key: tenant-id
        # BKE Cluster configuration
        - name: BKE_CLUSTER_ID
          value: "letbvcssxzusv4eg"
        - name: BKE_CLUSTER_TOKEN
          value: "KgrtTbXkdCe9awWE6DDV2Rm4ENo6jPTY"
        - name: BKE_JOIN_ENDPOINT
          value: "http://engine.api.k8saas.bizflycloud.vn/engine/cluster_join/letbvcssxzusv4eg"
        - name: BKE_LOG_ENDPOINT
          value: "http://engine.api.k8saas.bizflycloud.vn/engine/cluster_log/letbvcssxzusv4eg"
        # Additional configuration
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_ZONE
          value: "HN1"
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_DRIFT_DETECTION_ENABLED
          value: "true"
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_DRIFT_DETECTION_RECONCILE_INTERVAL
          value: "5m"
        - name: KARPENTER_CLOUD_PROVIDER_CONFIG_DRIFT_DETECTION_AUTO_REMEDIATE
          value: "true"