apiVersion: karpenter.bizflycloud.com/v1
kind: BizflyCloudNodeClass
metadata:
  name: default
spec:
  template: "Ubuntu 20.04.4 LTS"
  imageId: "5a821700-a184-4f91-8455-205d47d472c0"
  diskType: "SSD"
  rootDiskSize: 40
  vpcNetworkIds:
    - "e84362d6-0632-4950-87ac-e7bc7d74be6d"
  region: "HN"
  zone: "HN2"
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  # disruption:
  #   consolidationPolicy: WhenEmpty
  #   consolidateAfter: 30s
  template:
    spec:
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["nix.2c_3g", "nix.2c_2g", "nix.32c_64g"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["HN2"]
        # - key: "karpenter.bizflycloud.sh/image-id"
        #   operator: In
        #   values: ["ubuntu-20.04"]
      nodeClassRef:
        name: default
        kind: BizflyCloudNodeClass
        group: karpenter.bizflycloud.com

