apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
  template:
    metadata:
      labels:
        nodepool: default
    spec:
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["4c_8g", "8c_16g", "16c_32g"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["HN1-a", "HN1-b"]
        - key: "karpenter.bizflycloud.sh/image-id"
          operator: In
          values: ["ubuntu-20.04"]
      nodeClassRef:
        name: default
        kind: BizflyCloudNodeClass
        group: karpenter.bizflycloud.com