apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  labels:
    karpenter.bizflycloud.com/disk-type: HDD
    topology.kubernetes.io/zone: HN1
  name: default-2
spec:
  disruption:
    budgets:
    - nodes: "1"
      reasons:
      - Empty
      - Underutilized
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.bizflycloud.com
        kind: BizflyCloudNodeClass
        name: default
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - saving-plane
      - key: karpenter.bizflycloud.com/node-category
        operator: In
        values:
        - enterprise
      - key: karpenter.bizflycloud.com/disk-type
        operator: In
        values:
        - HDD
      - key: bizflycloud.com/kubernetes-version
        operator: In
        values:
        - v1.31.5
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - HN1
      startupTaints:
      - effect: NoExecute
        key: karpenter.sh/unregistered
        value: "true"
      - effect: NoSchedule
        key: karpenter.sh/disrupted
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
      - effect: NoSchedule
        key: node.cilium.io/agent-not-ready
      terminationGracePeriod: 30s